if("${ARG2}" STREQUAL "")
    message("SYNTAX: omega pack.[prepare|build|publish]")
    message("  Utilities for packaging omegalib and modules to installable binaries")
    message("  If you run pack without arguments, the command will execute")
    message("  pack.prepare, pack.build and pack.publish on the selected")
    message("  omegalib version")
    message("ARGUMENTS:")
    message("  - local-dir: name of local installation directory")
    message("EXAMPLES:")
    message("  > omega pack.prepare master")
    message("  > omega pack master")
    return()
endif()

include("${CMAKE_CURRENT_LIST_DIR}/pack.prepare.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pack.build.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pack.publish.cmake")
